version: "3"

services:
    terraform:
        image: marizmendi/terraform
        pull_policy: always
        volumes:
            - ./terraform:/terraform
            - certificate:/certificate
            - state:/state
        env_file: ./terraform/.env
        entrypoint: "sh /terraform/entrypoint.sh"
    nginx:
        image: nginx
        pull_policy: always
        volumes:
            - ./nginx:/etc/nginx/templates
            - certificate:/etc/certificate
        environment:
            HOST: "node"
            PORT: "8000"
        ports:
            - "443:443"
        restart: unless-stopped
        networks:
            - app
    ddclient:
        image: marizmendi/ddclient:latest
        pull_policy: always
        volumes:
            - ./ddclient:/ddclient
        env_file: ./ddclient/.env
        entrypoint: "sh /ddclient/entrypoint.sh"
    node:
        image: node:lts-alpine
        volumes:
            - ./node:/node
        entrypoint: "sh /node/entrypoint.sh"
        networks:
            - app

volumes:
    certificate:
    state:

networks:
    app:
