version: "3"

services:
    terraform:
        build: ./terraform
        volumes:
            - ./terraform:/terraform
            - certificate:/certificate
            - state:/state
        env_file: ./terraform/.env
        entrypoint: "sh /terraform/entrypoint.sh"
    nginx:
        image: nginx:stable
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - certificate:/etc/certificate
        ports:
            - "443:443"
        restart: always
    ddclient:
        build: ./ddclient
        volumes:
            - ./ddclient:/ddclient
        env_file: ./ddclient/.env
        entrypoint: "sh /ddclient/entrypoint.sh"

volumes:
    certificate:
    state:
