version: "3.8"

services:
    suricata:
        image: marizmendi/suricata
        restart: always
        environment:
        # For ET Pro ruleset replace "OPEN" with your OINKCODE
            - OINKCODE=OPEN
            - INTERFACE=wg0
        network_mode: "host"
        cap_add:
            - NET_ADMIN
            - SYS_NICE
            - NET_RAW
        volumes:
            - rpi-data:/var/log/suricata

    filebeat:
        image: marizmendi/filebeat
        environment:
            - ES_HOST=192.168.1.110
            - ES_PORT=9200
            - KIBANA_HOST=192.168.1.110
            - KIBANA_PORT=5601
        volumes:
            - rpi-data:/var/log/suricata

volumes:
    rpi-data: