apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certificate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: state
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
