apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certificate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Ki
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: state
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Ki
