apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: node
        image: node:lts-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        command:
          - /bin/sh
          - -c
          - cp -r /tmp/app /; cd app; npm install; npm start
        volumeMounts:
          - mountPath: /tmp/app/
            name: app
      volumes:
      - name: app
        configMap:
          name: node
