# https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/suricata/eve.json

    fields:
      event.type: suricata

  processors:
     - decode_json_fields:
         fields: [message]
         process_array: true
         overwrite_keys: true
         target: ""

  output.elasticsearch:
    hosts: ["${ES_HOST}:${ES_PORT}"]