apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  app.conf.template: |
    server {
        listen 443 ssl;
        server_tokens off;

        ssl_certificate /etc/certificate/certificate.pem;
        ssl_certificate_key /etc/certificate/privkey.pem;

        ssl_client_certificate /etc/certificate/origin-pull-ca.pem;
        ssl_verify_client on;

        set_real_ip_from 0.0.0.0/0;
        real_ip_header CF-Connecting-IP;

        location / {
            proxy_pass http://${HOST}:${PORT};
        }
    }
