apiVersion: v1
kind: Pod
metadata:
  name: node
  labels:
    name: node
spec:
  containers:
  - name: node
    image: node:lts-alpine
    command:
    - /bin/sh
    - -c
    - cp -r /tmp/app /; cd app; npm install; npm start
    volumeMounts:
    - mountPath: /tmp/app
      name: node
  volumes:
  - name: node
    configMap:
      name: node
