apiVersion: v1
kind: ConfigMap
metadata:
  name: node
data:
  package.json: |
    {
      "main": "index.js",
      "scripts": {
        "start": "node index.js"
      }
    }
  index.js: |
    const http = require('http');

    const requestListener = function (req, res) {
      res.writeHead(200, {"Content-Type": "text/plain"});
      res.end(req.headers["cf-connecting-ip"]);
    }

    const server = http.createServer(requestListener);
    server.listen(80);

  package-lock.json: |
    {
      "lockfileVersion": 1
    }
