apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: node
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      #   volumeMounts:
      #     - mountPath: /app/
      #       name: node-app
      # volumes:
      # - name: node-app
      #   configMap:
      #     name: app.conf.template
      #     items:
      #       - key: app.conf.template
      #         path: app.conf.template
