apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge
spec:
  selector:
    matchLabels:
      app: homebridge
  replicas: 1
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      hostNetwork: true
      containers:
      - name: homebridge
        image: oznu/homebridge:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8581
        volumeMounts:
          - mountPath: /homebridge
            name: homebridge
        env:
        - name: tz
          value: America/Chicago
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
      volumes:
      - name: homebridge
        persistentVolumeClaim:
          claimName: homebridge
