apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddclient
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ddclient
            image: marizmendi/ddclient
            env:
            - name: CLOUDFLARE_EMAIL
              value: manmar92@gmail.com
            - name: CLOUDFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: global_api_key
            - name: HOST
              value: arizxyz.com
            command:
            - /bin/sh
            - -c
            - mkdir /etc/ddclient/; envsubst < "/tmp/ddclient/ddclient.conf.template" > "/etc/ddclient/ddclient.conf"; /bin/ddclient --cache /var/cache/ddclient.cache
            volumeMounts:
            - mountPath: /tmp/ddclient
              name: ddclient
          volumes:
            - name: ddclient
              configMap:
                name: ddclient
          restartPolicy: OnFailure
