name: pi4

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Kubernetes CLI - kubectl
        uses: steebchen/kubectl@v2.0.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: '"apply -f app -f ddclient -f terraform -f game -f wireguard"'
